# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: self-hosted
  steps:
    - name: Rename file 
      run: |
        BRANCH=$(echo $GITHUB_REF | cut -d / -f 3)
        if [[ $BRANCH == "main" ]]; then
          rm -f file.txt
          
          
        elif [[ $BRANCH == "production" ]]; then
          mv oldfile.txt newfile.txt
          
        elif [[ $BRANCH == "preproduction" ]]; then
         mv oldfile.txt preprod.txt
         
       fi
